// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package jpid

import (
	"omniscient/api/jpid"
)

type ControllerV1 struct{}

func NewV1() jpid.IJpidV1 {
	return &ControllerV1{}
}
