// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"omniscient/internal/dao/internal"
)

// jpidDao is the data access object for the table jpid.
// You can define custom methods on it to extend its functionality as needed.
type jpidDao struct {
	*internal.JpidDao
}

var (
	// Jpid is a globally accessible object for table jpid operations.
	Jpid = jpidDao{internal.NewJpidDao()}
)

// Add your custom methods and functionality below.
